### ISSUE TITLE
DaggerActivityComponent不存在

### ISSUE THREAD

**Issue by LiJia92** [lguipeng/Notes#13]
导入工程到AS里，DaggerActivityComponent这个类不存在，却在MainActivity、NoteActivity等类中引用，导致报错。

**Comment by lguipeng** [comment]
rebuild一下

**Comment by LiJia92** [comment]
你仔细检查下你的源代码...源代码里都没有这个类，我怎么build也build不出来啊

**Comment by lguipeng** [comment]
这个类是dagger生成的。。。。。麻烦去看dagger在回来说
