### ISSUE TITLE
直接运行后，印象笔记绑定奔溃

### ISSUE THREAD

**Issue by zxk123** [lguipeng/Notes#19]

**Comment by zxk123** [comment]
是不是build 里面少了 几句这个buildConfigField "String", "EVERNOTE_CONSUMER_KEY", (project.hasProperty('EVERNOTE_CONSUMER_KEY') ? "\"$EVERNOTE_CONSUMER_KEY\"" : "\"Your consumer key\"")

**Comment by liongoodvery** [comment]
I have the same problem ,with the exception `java.lang.RuntimeException: Unable to start activity ComponentInfo{com.lguipeng.notes/com.lguipeng.notes.ui.SettingActivity}: java.lang.NullPointerException: activityComponent`

**Comment by Aimer1** [comment]
少了几个类文件,反编译里面的apk看看就知道了
