### ISSUE TITLE
 20150916clone最新版本到AS，点击运行按钮，报错

### ISSUE THREAD

**Issue by zolazhang** [lguipeng/Notes#4]
错误如下

Error:Execution failed for task ':app:compileDebugJava'.

> When running gradle with java 5, 6 or 7, you must set the path to jdk8, either with property retrolambda.jdk or environment variable JAVA8_HOME

请问，如何解决

**Comment by lguipeng** [comment]
项目里面用到lambda， 升级到jdk8就可以了
